Fix File Name

diff --git a/scripts/git-hooks/post-receive b/scripts/git-hooks/post-receive
--- a/scripts/git-hooks/post-receive
+++ b/scripts/git-hooks/post-receive
@@ -6,33 +6,39 @@ REPO_NAME=__REPO_NAME__
 COMPOSE_FILE=__COMPOSE_FILE__
 
 # Install Docker Engine if not available
-echo "Checking for Docker"
+echo "Info: Checking for Docker"
 if ! [ -x "$(command -v docker)" ]; then
     echo 'Info: Docker was not detected and is now being installed...' >&2
     curl -fsSL https://get.docker.com -o get-docker.sh
     sudo sh get-docker.sh
 fi
+if [ -x "$(command -v docker)" ]; then
+    echo 'Info: Docker seemes to be installed' >&2
+fi
 
 # Install docker-compose if not available
-echo "Checking for Docker-Compose"
+echo "Info: Checking for Docker-Compose"
 if ! [ -x "$(command -v docker-compose)" ]; then
     echo 'Info: docker-compose was not detected and is now being installed...' >&2
     sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
     sudo chmod +x /usr/local/bin/docker-compose
 fi
+if [ -x "$(command -v docker-compose)" ]; then
+    echo 'Info: Docker-Compose seemes to be installed' >&2
+fi
 
 
-echo "post-receive: Triggered."
+echo "post-receive.sh: Triggered."
 cd /opt/live/$REPO_NAME
 
-echo "post-receive: git check out…"
+echo "post-receive.sh: git check out…"
 git --git-dir=/opt/$REPO_NAME.git --work-tree=/opt/live/$REPO_NAME checkout production-readonly -f
 
 docker-compose -f "$COMPOSE_FILE" up -d --build
-echo "post-receive: Docker containers successfully recreated."
+echo "post-receive.sh: Docker containers successfully recreated."
 
 # Wait for containers to boot up.
-echo "post-receive: Validate deploy status…"
+echo "post-receive.sh: Validate deploy status…"
 sleep 8
 
 DEPLOY_FAILED=false
@@ -41,16 +47,16 @@ DEPLOY_FAILED=false
 for container in "$CONTAINER_VALIDATION_TARGETS"
 do
     if [[ -z $(docker ps -q --no-trunc | grep "$(docker-compose ps -q $container)") ]]; then
-        echo "post-receive: '$container' container did not restart properly!"
-        echo "post-receive: DEPLOY_FAILED"
+        echo "post-receive.sh: '$container' container did not restart properly!"
+        echo "post-receive.sh: DEPLOY_FAILED"
         DEPLOY_FAILED=true
         break;
     else
-        echo "post-receive: RESTARTED & VALIDATED SUCCESSFULLY: $container"
+        echo "post-receive.sh: RESTARTED & VALIDATED SUCCESSFULLY: $container"
     fi
 done
 
 if [ "$DEPLOY_FAILED" = false ]
 then
-    echo "post-receive: DEPLOY_COMPLETED"
+    echo "post-receive.sh: DEPLOY_COMPLETED"
 fi
